### ISSUE TITLE
Error initializing webview

### ISSUE THREAD

**Issue by delebru** [Bartmax/Youtube.Music#1]
Opening the exe gives an instant error and the app closes when the dialog is closed :( 

![image](https://user-images.githubusercontent.com/2726502/74332055-bd41b800-4d73-11ea-9afb-1205ad8d38ab.png)

**Comment by Bartmax** [comment]
Do you have Edge (chrominium version) installed?
This is a requirement for WebWindow which this app runs on top of.

Take a look at this issue
https://github.com/SteveSandersonMS/WebWindow/issues/59
